$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-deployment
endpoint_name: pipeline-endpoint-2
model: azureml:log-regression:11
instance_type: Standard_DS3_v2
instance_count: 1
