$schema: https://azuremlschemas.azureedge.net/latest/managedOnlineDeployment.schema.json
name: mlflow-sklearn-deployment-3
endpoint_name: exercise-endpoint
model: azureml:job-output-model-mlflow:1
instance_type: Standard_DS2_v2
instance_count: 1
